### ISSUE TITLE
503 error and AttributeError: module 'google.auth.transport' has no attribute 'requests'

### ISSUE THREAD

**Issue by Winthan** [googleapis/python-api-core#107]
Getting the following error when I am running with python for prediction, even I have added JSON file for the cloud auth key. Some other machines work my script without any problem though. 

```
runfile('C:/bot/googlex.py', wdir='C:/bot')
collecting data
Traceback (most recent call last):

  File "c:\programdata\anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 58, in error_remapped_callable
    return callable_(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)

  File "C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "502:Bad Gateway"
	debug_error_string = "{"created":"@1606950672.430000000","description":"Error received from peer ipv4:172.217.14.234:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"502:Bad Gateway","grpc_status":14}"
>


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\bot\googlex.py", line 278, in <module>
    predict_tabular_regression_sample(

  File "C:\bot\googlex.py", line 261, in predict_tabular_regression_sample
    response = client.predict(

  File "c:\programdata\anaconda3\lib\site-packages\google\cloud\aiplatform_v1beta1\services\prediction_service\client.py", line 438, in predict
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)

  File "c:\programdata\anaconda3\lib\site-packages\google\api_core\gapic_v1\method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)

  File "c:\programdata\anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 60, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)

  File "<string>", line 3, in raise_from

ServiceUnavailable: 503 502:Bad Gateway


runfile('C:/bot/googlex.py', wdir='C:/bot')
collecting data
Traceback (most recent call last):

  File "C:\bot\googlex.py", line 278, in <module>
    predict_tabular_regression_sample(

  File "C:\bot\googlex.py", line 251, in predict_tabular_regression_sample
    client = aiplatform.gapic.PredictionServiceClient(client_options=client_options)

  File "c:\programdata\anaconda3\lib\site-packages\google\cloud\aiplatform_v1beta1\services\prediction_service\client.py", line 327, in __init__
    self._transport = Transport(

  File "c:\programdata\anaconda3\lib\site-packages\google\cloud\aiplatform_v1beta1\services\prediction_service\transports\grpc.py", line 160, in __init__
    self._grpc_channel = type(self).create_channel(

  File "c:\programdata\anaconda3\lib\site-packages\google\cloud\aiplatform_v1beta1\services\prediction_service\transports\grpc.py", line 217, in create_channel
    return grpc_helpers.create_channel(

  File "c:\programdata\anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 276, in create_channel
    composite_credentials = _create_composite_credentials(

  File "c:\programdata\anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 223, in _create_composite_credentials
    request = google.auth.transport.requests.Request()

AttributeError: module 'google.auth.transport' has no attribute 'requests'
```

**Comment by busunkim96** [comment]
Hi,

The 503s are most likely connectivity issues specific to that environment, especially if you can get the script to run in other machines.

As for the last error, I'm not quite sure what could be causing it. That requests transport has been there for a long time so any recent version of `google-auth` should be sufficient.

Can you please share:

(1) The Python version you are using.
(2) A code snippet.
(3) The versions of the libraries you have installed.`pip freeze`

(Tentatively moving to aiplatform, but may end up coming back to api-core.)
