### ISSUE TITLE
got an unexpected keyword argument 'default_scopes'

### ISSUE THREAD

**Issue by Pavan23-star** [googleapis/python-api-core#263]
raised unexpected: ValueError("invalid truth value '/home/.../.../.../../.../config/googleanalyticskey/clinx-300912-e1f14afa28a3.json'")
Traceback (most recent call last):
  File "/home/clinx/.virtualenvs/clinxenv/lib/python3.7/site-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/clinx/.virtualenvs/clinxenv/lib/python3.7/site-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/clinx/clinxProjects/clinx/clinx/analytics/tasks.py", line 81, in update_website_analytics_count_by_property_id
    client = BetaAnalyticsDataClient()
  File "/home/clinx/.virtualenvs/clinxenv/lib/python3.7/site-packages/google/analytics/data_v1beta/services/beta_analytics_data/client.py", line 282, in __init__
    util.strtobool(os.getenv("GOOGLE_API_USE_CLIENT_CERTIFICATE", "false"))
  File "/usr/lib/python3.7/distutils/util.py", line 307, in strtobool
    raise ValueError("invalid truth value %r" % (val,))

**Comment by allenporter** [comment]
Hi, seeing similar reports from folks running versions greater that `1.25.0` in https://github.com/home-assistant/core/issues/55687 

e.g. 
```
...
  File "/home/allen/home-assistant-core/venv/lib/python3.8/site-packages/google/
api_core/grpc_helpers.py", line 306, in create_channel                          
    composite_credentials = _create_composite_credentials(                      
  File "/home/allen/home-assistant-core/venv/lib/python3.8/site-packages/google/
api_core/grpc_helpers.py", line 236, in _create_composite_credentials           
    credentials = google.auth.credentials.with_scopes_if_required( 
TypeError: with_scopes_if_required() got an unexpected keyword argument 'default
_scopes'                                                                        
```

```
>>> import google.api_core
>>> google.api_core.__version__
'1.31.0'
```

```
$ pip3 freeze  | egrep 'google|grpc'
google-api-core==1.31.0
google-api-python-client==1.6.4
google-auth==1.35.0
google-auth-oauthlib==0.4.6
google-cloud-pubsub==2.1.0
google-cloud-texttospeech==0.4.0
google-nest-sdm==0.3.6
googleapis-common-protos==1.52.0
googlemaps==2.5.1
grpc-google-iam-v1==0.12.3
grpcio==1.31.0
```

**Comment by allenporter** [comment]
My mistake, my local reproduction of this was incorrect.  Here is some more detail:
```
>>> import google.auth.credentials
>>> google.auth.credentials.__file__
'/path/to/google-auth-python/.../auth/credentials.py'
```
This pointed to a local editable install with `pip install -e /path/to/google-auth-python` as I was doing local development a few months ago and using an old version, and this appears different than the issue I referenced.
